### ISSUE TITLE
Add Manifest functionality to this Python client API

### ISSUE THREAD

**Issue by kotarf** [googleapis/python-storage-transfer#45]
**Is your feature request related to a problem? Please describe.**
The Python client and REST API don't have feature parity w.r.t Manifests.

 **Describe the solution you'd like**
Add Manifest functionality to this Python client API, which is already present in the REST API.

_REST API (supports Manifests)_
https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#transfermanifest

_Client API (doesn't seem to)_
https://cloud.google.com/python/docs/reference/storagetransfer/latest/google.cloud.storage_transfer_v1.types.TransferSpec

 **Additional context**
Sorry if this is on the radar already.

**Comment by cojenco** [comment]
Hi @kotarf, the storage transfer manifest feature is on our radar and planned for H122. Stay tuned, thanks!

**Comment by danielbankhead** [comment]
Hey @kotarf - the transfer manifest functionality is now available with recent releases of the client library.

Here's a usage example:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/ecdaa934908f11ff37a8dd48c0cca5b32559b863/storagetransfer/manifest_request.py#L29-L77

Thanks for your patience!
