### ISSUE TITLE
feat: is there an ability to label scheduled transfers ?

### ISSUE THREAD

**Issue by terekete** [googleapis/python-storage-transfer#7]
**Is your feature request related to a problem? Please describe.**
Unsure if this exists already, if not this would be a feature request.
An ability to label different storage transfer jobs performed as scheduled queries. Is there a means to add labels to each transfer config.

 **Describe the solution you'd like**
One would see a label similar to those seen in Big Query.

 **Describe alternatives you've considered**
N/A

 **Additional context**
Does this exist already ?

**Comment by parthea** [comment]
Hi @terekete ,

Please can you share an example of the label feature that you use in BigQuery or a link to the specific section in the BigQuery docs? 

To increase visibility of this feature request, please also file a bug on the public issue tracker for the Storage Transfer Service [here](https://issuetracker.google.com/issues/new?component=815827&template=1395449) which is found on the [support page](https://cloud.google.com/storage-transfer/docs/getting-support) for Storage Transfer Service.

**Comment by JesseLovelace** [comment]
Transfer Service has a job description field, but no key-value pair label like BigQuery has. I can bring the feature request up with the team

**Comment by terekete** [comment]
thanks that would be great

**Comment by cojenco** [comment]
This feature request is now being tracked in https://issuetracker.google.com/issues/277639121
